# Generated by Django 5.2.1 on 2025-05-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('like-new', 'Like New'), ('good', 'Good'), ('used', 'Used'), ('poor', 'Poor')], max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('non-fiction', 'Non-fiction'), ('romance', 'Romance'), ('mystery', 'Mystery'), ('fantasy', 'Fantasy'), ('biography', 'Biography'), ('sci-fi', 'Sci-Fi'), ('history', 'History'), ('children', 'Children'), ('self-help', 'Self Help'), ('islamic', 'Islamic'), ('drama', 'Drama'), ('thriller', 'Thriller'), ('adventure', 'Adventure'), ('classic', 'Classic'), ('education', 'Education'), ('poetry', 'Poetry'), ('comics', 'Comics'), ('art', 'Art'), ('travel', 'Travel')], max_length=100),
        ),
    ]
