# Generated by Django 5.2.1 on 2025-05-25 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rated_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='rating',
            name='exchange_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.exchangerequest'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
